### ISSUE TITLE
fix(ci): deployment failed due to connection timeout

### ISSUE THREAD

**Issue by dargmuesli** [flipdot/app-dashboard#15]
The continuous deployment seems to not work right now: `ssh: connect to host *** port ***: Connection timed out` ([example log](https://github.com/flipdot/app-dashboard/actions/runs/11897694542/job/33152539922))

**Comment by soerface** [comment]
The webserver is running in our space. Recently someone worked on our DSL connection. Could you try again?

**Comment by dargmuesli** [comment]
Oh, works again now :)
